config/routes.rb
Rails.application.routes.draw do
  resources :ponts, only: %i[index new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "ponts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pont.rb
class Pont < ApplicationRecord
  validates :body, presence: true, length: {minimum: 2}

  def formatted_created_at
    self.created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ponts_controller.rb
class PontsController < ApplicationController
  before_action :set_pont, only: %i[ show edit update destroy ]

  # GET /ponts or /ponts.json
  def index
    @ponts = Pont.all.order(created_at: :desc)
  end

  # GET /ponts/1 or /ponts/1.json
  def show
  end

  # GET /ponts/new
  def new
    @pont = Pont.new
    @ponts = Pont.all
  end

  # GET /ponts/1/edit
  def edit
  end

  # POST /ponts or /ponts.json
  def create
    @pont = Pont.new(pont_params)

    respond_to do |format|
      if @pont.save
        format.html { redirect_to pont_url(@pont), notice: "Pont was successfully created." }
        format.turbo_stream {render :create, locals: {pont: @pont}}
        format.json { render :show, status: :created, location: @pont }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream {render :new, status: :unprocessable_entity, locals: {pont: @pont}}
        format.json { render json: @pont.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponts/1 or /ponts/1.json
  def update
    respond_to do |format|
      if @pont.update(pont_params)
        format.html { redirect_to pont_url(@pont), notice: "Pont was successfully updated." }
        format.json { render :show, status: :ok, location: @pont }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pont.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponts/1 or /ponts/1.json
  def destroy
    @pont.destroy

    respond_to do |format|
      format.html { redirect_to ponts_url, notice: "Pont was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pont
      @pont = Pont.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pont_params
      params.require(:pont).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponts_helper.rb
module PontsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Понты дороже денег</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
        <% flash.each do |key , value| %>
          <%= tag.div value, class: "alert alert-success #{key} my-3", role: 'alert' %>
        <% end %>  
        <%= yield %>
    </div>
  </body>
</html>

app/views/ponts/_form.html.erb
<%= turbo_frame_tag "new_pont" do %>
  <%= form_with(model: pont) do |form| %>
      <% if pont.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(pont.errors.count, "error") %> prohibited this pont from being saved:</h2>

        <ul>
          <% pont.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

    <div class="mb-2 col-lg-6 mx-auto">     
      <div class="mb-2">
        <%= form.text_area :body, size: "10x5", placeholder: "Начни печатать понты здесь", class:'form-control'  %>
      </div>
    </div>

    <div class="mb-2 ">
      <%= form.submit "Понтануться", class: "btn btn-outline-success btn-lg px-4 gap-3"%>
    </div>
  <% end %>
<% end %>

app/views/ponts/_pont.html.erb
<div id="<%= dom_id pont %>">
  <div class="card shadow-sm my-3 rounded-4 border-0">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p class="lead fs-4"><%=sanitize pont.body %></p>
      </blockquote>
    </div>
  </div>
</div>

app/views/ponts/create.turbo_stream.erb
<%= turbo_stream.prepend "ponts" do %>
 <%= render partial: "pont", locals: {pont: @pont} %>
<% end %>


<%= turbo_stream.replace "new_pont",
    partial: "form",
    locals: {pont: Pont.new} %>

app/views/ponts/edit.html.erb
<h1>Editing pont</h1>

<%= render "form", pont: @pont %>

<br>

<div>
  <%= link_to "Show this pont", @pont %> |
  <%= link_to "Back to ponts", ponts_path %>
</div>

app/views/ponts/index.html.erb
<div class="row text-center mt-5">
  <div class="col-1 col-sm-1"></div>
  <div class="col-10 col-sm-10">
    
    <h1 class="display-5 fw-bold text-body-emphasis">Время понтов!</h1>
    <p class="lead mb-4"> Прошедший год был наверняка насыщен событиями, и уверен, что у каждого из вас есть чем похвастаться. Давайте делиться своими яркими моментами здесь, анонимно. Без скромности расскажите о своих достижениях за этот год – будем вместе создавать коллекцию понтов! И помните, что ваш понт может вдохновить кого-то другого на крутые свершения.</p>
    <%= render "form", pont: Pont.new %>

    <div class="mt-4">
      <h1 class="display-5 fw-bold  text-center text-body-emphasis">Другие понты:</h1>
    </div>

    <div id="ponts">
      <% @ponts.each do |pont| %>
        <%= render pont %>
      <% end %>
    </div>

  </div>

  <div class="col-1 col-sm-1"></div>
</div>

app/views/ponts/new.html.erb
<div class="row text-center mt-5">
  <div class="col-2 col-sm-2">
  </div>

  <div class="col-8 col-sm-8">

      <h1 class="display-5 fw-bold text-body-emphasis">Время понтов!</h1>

      <div class="col-lg-10">
        <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
      </div>
      <%= render "form", pont: @pont %>

      <br>

      <div class="mt-4">
        <h1 class="display-5 fw-bold text-body-emphasis">Другие понты:</h1>
      </div>
      
      <% @ponts.each do |item| %>
        <div class="card shadow my-5 border-0">
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p class="lead fs-4"><%=item.body %></p>
            </blockquote>
          </div>
        </div>
      <% end %>
  </div>

  <div class="col-2 col-sm-2">
  </div>

</div>

app/views/ponts/new.turbo_stream.erb
<%= turbo_stream.replace "new pont" do %>
  <%= render partial: "form", locals: {pont: @pont} %>
<% end %>

app/views/ponts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pont %>

<div>
  <%= link_to "Edit this pont", edit_pont_path(@pont) %> |
  <%= link_to "Back to ponts", ponts_path %>

  <%= button_to "Destroy this pont", @pont, method: :delete %>
</div>